// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnptlhgfplqisbnumzpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJucHRsaGdmcGxxaXNibnVtenBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTE1ODgsImV4cCI6MjA3MzUyNzU4OH0.sAnueuwUgXQn1HaB5y56RXcHlOHBEtA9tCW_7DrOs78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});